default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: root
  host: mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_app_development


test:
  <<: *default
  database: rails_app_test

production:
  <<: *default
  database: rails_app_production